#!/usr/bin/env bash

docker run -it -v $PWD:/app composer "${@:1}"
rooted=`ls -lRG |grep root | awk '{print $NF}'`
list=`echo -e "\e[38;5;196m["$rooted"]\e[0m" | sed "s/ /, /g"`
echo "Found root files & directories: $list"
if [[ ! -z "$rooted" ]]; then
	sudo chown -R $USER:$USER .
	list=`echo -e "\e[38;5;82m["$rooted"]\e[0m" | sed "s/ /, /g"`
	echo "Files & directories changed owner: $list"
fi
